### ISSUE TITLE
Feature request: remove need to include -FlashArray in every cmdlet call

### ISSUE THREAD

**Issue by MasterOfTheHat** [purestorage/PowerShell-Toolkit#7]
The way the module is written requires every cmdlet call to include the -FlashArray parameter and the -Session parameter. From what it looks like in the code, the functions aren't even using the FlashArray parameter, but they've all been swapped over to using the PureStorageURIBase global variable. Based on that, the FlashArray parameter can be removed from almost all of the functions.

**Comment by tlindsay42** [comment]
+1 - Nice!

**Comment by barkz** [comment]
I've kept this parameter around since I used it from the beginning in the early cmdlets. I retained to ensure backward compatibility for customers using the earlier incremental releases. I have now marked the FlashArray parameter as optional (Mandatory=$False) so no existing scripts need to be changed. We are testing all of the cmdlets to ensure there are no issues. I should roll this out no later than Monday, March 23, 2015 (Target release v2.5.0.323).
